# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Accuracy Test Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
      GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
      GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
      GOOGLE_SPEECH_API_KEY: ${{ secrets.GOOGLE_SPEECH_API_KEY }}
      WATSON_TTS_KEY: ${{ secrets.WATSON_TTS_KEY }}
      WATSON_TTS_INSTANCE_URL: ${{ secrets.WATSON_TTS_INSTANCE_URL }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_TABLE: ${{ secrets.MYSQL_TABLE }}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: pnpm install
      run: |
        pnpm install
    - name: accuracy test
      run: |
        pnpm run batch
